version: '3.2'

services: 
    redis:
        image: redis:latest
    web:
        container_name: "javaapp"
        build: .
        command: ["java", "-jar", "-Xms512m", "-Xmx512m", "-Dspring.profiles.active=prod", "/app/application.jar"]
        ports:
            - "8080:8080"
        links:
            - redis