---
# This playbook deploys the whole application stack in this site.

- name: install docker and compose
  become: true
  hosts: localhost
  roles:
    - geerlingguy.docker

- name: configure, deploy and run the java microservice
  become: true
  hosts: localhost
  roles:
    - web