---
# This playbook deploys the whole application stack in this site.

- roles:
  - geerlingguy.docker

- name: configure, deploy and run the java microservice
  become: true
  hosts: localhost
  roles:
    - web